const todoActionType = {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  REFRESH_TODOS: "REFRESH_TODOS",
  LOADING_STATE: "LOADING_STATE",
  INITIAL_LOADING: "INITIAL_LOADING",
};

export default todoActionType;
